name: Whitelabel Design System

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Preparar pasta do artifact
        run: |
          # Verifica se a pasta dist existe
          if [ -d "dist" ]; then
            mkdir -p build
            cp -R dist build/  # Copia a pasta "dist" para dentro de "build"
          else
            echo "A pasta 'dist' não foi gerada pelo build."
            exit 1
          fi
      - name: Upload da pasta build
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download da pasta build
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: .
      - name: Listar estrutura para debug
        run: ls -R
      - name: Preparar pasta dist para publicação
        run: |
          if [ -d "build/dist" ]; then
            rm -rf dist
            mv build/dist .
          else
            echo "build/dist não foi encontrado. Verifique a estrutura acima."
            exit 1
          fi
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
