name: Whitelabel Design System

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - name: Preparar pasta do artifact
        run: |
          mkdir -p build
          cp -R dist build/  # agora a pasta "dist" estará dentro de "build"
      - name: Upload da pasta build
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Download da pasta build
        uses: actions/download-artifact@v4
        with:
          name: build-folder
          path: .
      - name: Verificar estrutura
        run: ls -R
      # Se desejar, mova a pasta "dist" para a raiz:
      - name: Preparar pasta dist para publicação
        run: |
          rm -rf dist
          mv build/dist .
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
